config/routes.rb
Rails.application.routes.draw do
  resources :robots
  root 'robots#show'
  post 'bot_positions/place'
  post 'bot_positions/right'
  post 'bot_positions/left'
  post 'bot_positions/up'
  post 'bot_positions/down'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bot_position.rb
class BotPosition < ApplicationRecord
	belongs_to :robot
end

app/models/robot.rb
class Robot < ApplicationRecord
	has_one :bot_position
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	add_flash_types :info, :error, :warning
end

app/controllers/bot_positions_controller.rb
class BotPositionsController < ApplicationController
  before_action :get_robot

  def index
  end

  def place
    @robot.bot_position.update(x_axis: 0, y_axis: 0)
    flash[:notice] = "Robot has been placed "
    redirect_to :root
  end

  def right
    x_axis = @robot.bot_position.x_axis
    unless x_axis >= 4
      if @robot.bot_position.update(x_axis: x_axis+1)
        flash[:notice] = "Moved to right"
      end
    else
      flash[:notice] = "Action not valid"
    end
      redirect_to :root
  end

  def left
    x_axis = @robot.bot_position.x_axis
    if x_axis > 0
      if @robot.bot_position.update(x_axis: x_axis-1)
        flash[:notice] = "Moved to left"
      end
    else
      flash[:notice] = "Action not valid"
    end
      redirect_to :root
  end

  def up
    y_axis = @robot.bot_position.y_axis
    if y_axis == 0 || y_axis == 1
      @robot.bot_position.update(y_axis: 0)
      flash[:notice] = "Moved upwards"
    else
      flash[:notice] = "Action not valid"
    end
    redirect_to :root
  end

  def down
    y_axis = @robot.bot_position.y_axis
    if y_axis == 0 || y_axis == 1
      @robot.bot_position.update(y_axis: 1)
      flash[:notice] = "Moved downwards"
    else
      flash[:notice] = "Action not valid"
    end
    redirect_to :root
  end

  private

  def get_robot
    @robot = Robot.find_by(params[:robot_id])
  end
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
  before_action :set_robot, only: %i[ show edit update destroy ]

  # GET /robots or /robots.json
  def index
    @robots = Robot.all
  end

  # GET /robots/1 or /robots/1.json
  def show
    @x_axis = @robot.bot_position.x_axis
    @y_axis = @robot.bot_position.y_axis
  end

  # GET /robots/new
  def new
    @robot = Robot.new
  end

  # GET /robots/1/edit
  def edit
  end

  # POST /robots or /robots.json
  def create
    @robot = Robot.new(robot_params)

    respond_to do |format|
      if @robot.save
        format.html { redirect_to robot_url(@robot), notice: "Robot was successfully created." }
        format.json { render :show, status: :created, location: @robot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @robot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /robots/1 or /robots/1.json
  def update
    respond_to do |format|
      if @robot.update(robot_params)
        format.html { redirect_to robot_url(@robot), notice: "Robot was successfully updated." }
        format.json { render :show, status: :ok, location: @robot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @robot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /robots/1 or /robots/1.json
  def destroy
    @robot.destroy

    respond_to do |format|
      format.html { redirect_to robots_url, notice: "Robot was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_robot
      @robot = Robot.find(Robot.last.id)
    end

    # Only allow a list of trusted parameters through.
    def robot_params
      params.require(:robot).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bot_positions_helper.rb
module BotPositionsHelper

def x_position(robot, index)
	if robot.bot_position.x_axis == 0 && robot.bot_position.y_axis == 0	&& index == 0
		return 'active'
	elsif robot.bot_position.x_axis == 1 && index == 1 && robot.bot_position.y_axis == 0
		return 'active'
	elsif robot.bot_position.x_axis == 2 && index == 2 && robot.bot_position.y_axis == 0
		return 'active'
	elsif robot.bot_position.x_axis == 3 && index == 3 && robot.bot_position.y_axis == 0
		return 'active'
	elsif robot.bot_position.x_axis == 4 && index == 4 && robot.bot_position.y_axis == 0
		return 'active'
	end
end

def y_position(robot, index)
	if robot.bot_position.y_axis == 1 && index == 0 && robot.bot_position.x_axis == 0
		return 'active'
	elsif 
		robot.bot_position.y_axis == 1 && index == 1 && robot.bot_position.x_axis == 1
		return 'active'
	elsif robot.bot_position.y_axis == 1 && index == 2 && robot.bot_position.x_axis == 2
		return 'active'
	elsif robot.bot_position.y_axis == 1 && index == 3 && robot.bot_position.x_axis == 3	
		return 'active'
	elsif robot.bot_position.y_axis == 1 && index == 4 && robot.bot_position.x_axis == 4
		return 'active'
	end
end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tablebot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div class="alert alert-warning">
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/robots/show.html.erb
<h1>Robot</h1>
<%= link_to 'Move', bot_positions_right_path(robot_id: @robot), method: :post %> |
<%= link_to 'Right', bot_positions_right_path(robot_id: @robot), method: :post %> |
<%= link_to 'Left', bot_positions_left_path(robot_id: @robot), method: :post %> |
<%= link_to "Place", bot_positions_place_path(robot_id: @robot), method: :post %>
<br>
<br>
<%= link_to "Up", bot_positions_up_path(robot_id: @robot), method: :post %> | 
<%= link_to "Down", bot_positions_down_path(robot_id: @robot), method: :post %>
<table>
  <tr>
    <% 5.times do |index| %>
      <td class="<%= x_position(@robot ,index) %>" ><%= index+1 %></td>
    <% end %>
  </tr>
  <tr>
    <% 5.times do |index| %>
      <td class="<%= y_position(@robot, index)%>"><%= index+1 %></td>
    <% end %>
  </tr>
  </tr>
</table>
<style type="text/css">
  td {
    padding: 50px;
  }
  .active {
    background: lightgrey;
  }
</style>